#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Récupérer le nom de la branche actuelle
current_branch=$(git symbolic-ref --short HEAD)

# Vérifier si on essaie de pusher sur master
if [ "$current_branch" = "master" ]; then
  echo "❌ [PROTECTION] Interdit de pusher directement sur la branche 'master'."
  echo "👉 Créez une branche de fonctionnalité (ex: feature/mon-dev) et ouvrez une Pull Request."
  exit 1
fi

echo "🛠 Vérification de la qualité avant push sur $current_branch..."

# On lance les vérifications
npm run typecheck && npm run build